import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

const FALLBACK = 'Not provided';

const formatValue = (value) => {
  if (value === null || value === undefined || value === '') return FALLBACK;
  if (Array.isArray(value)) return value.join(', ');
  if (typeof value === 'object') return JSON.stringify(value);
  return String(value);
};

const formatDate = (value) => {
  const date = value ? new Date(value) : new Date();
  const safeDate = Number.isNaN(date.getTime()) ? new Date() : date;
  return safeDate.toISOString().slice(0, 10);
};

const slugify = (value) =>
  formatValue(value)
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '') || 'prescription';

const parseMedicationRows = (medications) => {
  if (Array.isArray(medications)) {
    return medications.map((medicine) => [
      formatValue(medicine.name || medicine.medicine_name || medicine.medicine),
      formatValue(medicine.dosage || medicine.dose),
      formatValue(medicine.frequency),
      formatValue(medicine.duration),
    ]);
  }

  if (typeof medications === 'string') {
    try {
      const parsed = JSON.parse(medications);
      if (Array.isArray(parsed)) return parseMedicationRows(parsed);
    } catch {
      return [[medications, FALLBACK, FALLBACK, FALLBACK]];
    }
  }

  return [[formatValue(medications), FALLBACK, FALLBACK, FALLBACK]];
};

const addSection = (doc, title, body, x, y) => {
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(11);
  doc.text(title, x, y);
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(10);
  doc.text(formatValue(body), x, y + 6, { maxWidth: 180 });
};

export const downloadPrescriptionPdf = (prescription) => {
  const doc = new jsPDF();
  const pageHeight = doc.internal.pageSize.getHeight();
  const prescriptionDate = formatDate(prescription?.created_at);
  const doctorName = formatValue(prescription?.doctor_name);

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(18);
  doc.setTextColor(15, 118, 110);
  doc.text('Doctor Hub', 14, 18);
  doc.setFontSize(15);
  doc.setTextColor(15, 23, 42);
  doc.text('Prescription', 14, 28);
  doc.line(14, 34, 196, 34);

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(10);
  doc.text(`Date: ${prescriptionDate}`, 14, 44);
  doc.text(`Doctor: ${doctorName}`, 14, 52);
  doc.text(`Specialization: ${formatValue(prescription?.doctor_specialisation || prescription?.specialisation)}`, 14, 60);
  doc.text(`Patient: ${formatValue(prescription?.patient_name)}`, 110, 44);
  doc.text(`Email: ${formatValue(prescription?.patient_email)}`, 110, 52);

  addSection(doc, 'Diagnosis', prescription?.diagnosis_notes, 14, 76);
  addSection(doc, 'Symptoms', prescription?.symptoms, 14, 100);

  autoTable(doc, {
    startY: 124,
    head: [['Medicine Name', 'Dosage', 'Frequency', 'Duration']],
    body: parseMedicationRows(prescription?.medications),
    theme: 'grid',
    headStyles: { fillColor: [15, 118, 110] },
    styles: { fontSize: 9, cellPadding: 3 },
  });

  const notesY = Math.min((doc.lastAutoTable?.finalY || 154) + 14, 235);
  addSection(
    doc,
    'Additional Notes',
    prescription?.additional_notes || prescription?.dosage_instructions,
    14,
    notesY
  );

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9);
  doc.setTextColor(100, 116, 139);
  doc.text('Generated by Doctor Hub', 14, pageHeight - 18);
  doc.text(`Generated: ${new Date().toLocaleString()}`, 14, pageHeight - 11);

  doc.save(`prescription-${slugify(doctorName)}-${prescriptionDate.replace(/\//g, '-')}.pdf`);
};
