import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

const currency = (value) => `$${Number(value || 0).toLocaleString()}`;
const count = (value) => Number(value || 0).toLocaleString();

const monthlyRows = (data) => {
  const users = new Map((data.monthly_user_growth || []).map((row) => [row.month || row.label, row]));
  const revenue = new Map((data.monthly_revenue || []).map((row) => [row.month || row.label, row]));
  const appointments = new Map((data.monthly_appointments || []).map((row) => [row.month || row.label, row]));
  const keys = [...new Set([...users.keys(), ...revenue.keys(), ...appointments.keys()])];

  return keys.map((key) => {
    const userRow = users.get(key) || {};
    const revenueRow = revenue.get(key) || {};
    const appointmentRow = appointments.get(key) || {};
    return [
      userRow.label || revenueRow.label || appointmentRow.label || key,
      count(userRow.users),
      currency(revenueRow.revenue),
      count(appointmentRow.appointments),
    ];
  });
};

export const downloadAnalyticsReportPdf = (data, generatedAt = new Date()) => {
  const doc = new jsPDF();
  const pageHeight = doc.internal.pageSize.getHeight();
  const date = generatedAt.toISOString().slice(0, 10);
  const roles = data.user_distribution || {};
  const appointments = data.appointment_summary || {};
  const payments = data.payment_analytics || {};
  const totalUsers = Object.values(roles).reduce((sum, value) => sum + Number(value || 0), 0);

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(18);
  doc.setTextColor(15, 118, 110);
  doc.text('Doctor Hub', 14, 18);
  doc.setFontSize(15);
  doc.setTextColor(15, 23, 42);
  doc.text('Analytics and Reports', 14, 28);
  doc.line(14, 34, 196, 34);

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(10);
  doc.text(`Report date: ${date}`, 14, 44);
  doc.text(`Generated: ${generatedAt.toLocaleString()}`, 110, 44);

  autoTable(doc, {
    startY: 54,
    head: [['Metric', 'Value']],
    body: [
      ['Total Revenue', currency(payments.total_revenue)],
      ['Total Users', count(totalUsers)],
      ['Total Appointments', count(appointments.total)],
      ['Total Payments', count(payments.total)],
      ['Verified Payments', count(payments.verified)],
      ['Pending Payments', count(payments.pending)],
      ['Rejected Payments', count(payments.rejected)],
      ['Patients', count(roles.patient)],
      ['Doctors', count(roles.doctor)],
      ['Assistants', count(roles.assistant)],
      ['Admins', count(Number(roles.admin || 0) + Number(roles.super_admin || 0))],
      ['Pending Appointments', count(appointments.pending)],
      ['Confirmed Appointments', count(appointments.confirmed)],
      ['Completed Appointments', count(appointments.completed)],
      ['Cancelled Appointments', count(appointments.cancelled)],
    ],
    theme: 'grid',
    headStyles: { fillColor: [15, 118, 110] },
    styles: { fontSize: 9, cellPadding: 2.5 },
  });

  autoTable(doc, {
    startY: (doc.lastAutoTable?.finalY || 150) + 10,
    head: [['Month', 'New Users', 'Revenue', 'Appointments']],
    body: monthlyRows(data),
    theme: 'grid',
    headStyles: { fillColor: [37, 99, 235] },
    styles: { fontSize: 8, cellPadding: 2.3 },
  });

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9);
  doc.setTextColor(100, 116, 139);
  doc.text('Generated by Doctor Hub', 14, pageHeight - 18);
  doc.text(`Generated: ${generatedAt.toLocaleString()}`, 14, pageHeight - 11);

  doc.save(`doctor-hub-analytics-report-${date}.pdf`);
};
